### PR TITLE
Crytic properties

### PR DESCRIPTION
**Pull request by aviggiano**
# Description

- Add https://github.com/crytic/properties to the project
- Add echidna to CI and run multiple modes in parallel
- Restructure the project for better maintainability
- Add [remote-echidna](https://github.com/aviggiano/remote-echidna) sample workflow

# Notes

The out-of-the-box properties from `CryticERC4626PropertyTests` correctly identify the rounding issues #47 and #48 also found on [OpenZeppelin's first audit](https://github.com/pods-finance/yield-contracts/blob/main/audits/2022-11-15_OpenZeppelin_Pods.pdf). Simply reverting the changes of PR #46 will make the fuzzy tests fail in under 10,000 iterations.

### CODE REVIEW

**Comment by aviggiano** [comment]
Ready for review @Robsonsjre

**Comment by aviggiano** [comment]
@Robsonsjre added remote-echidna setup

**Review by Robsonsjre — APPROVED** [review]

**Comment by Robsonsjre** [comment]
Approved. Although I didn't understand where you are using EC2 and S3 secret keys in the script

**Comment by aviggiano** [comment]
It's on another repo

https://github.com/aviggiano/remote-echidna

**Pull request merged**
