### PR TITLE
Fix invariant tests

### PR DESCRIPTION
**Pull request by aviggiano**
# Description

This pull request fixes the invariant tests from `STETHVaultInvariants.sol`

# Summary of changes

### 1. Change state variables from public to private

The previous setup simply extended from `STETHVault`, which exposed a large number of `public` and `external` functions to echidna, taking forever to process. 

```
Tests found: 70
Seed: 3379254151187803815
Unique instructions: 7551
Unique codehashes: 3
Corpus size: 3
```

For example, none of those made sense to be tested:

```
assertion in INVESTOR_RATIO(): fuzzing (3858/100000)
assertion in controller(): fuzzing (3858/100000)
assertion in $configuration(): fuzzing (3858/100000)
```

Not even an `r3.2xlarge` instance (32 GB RAM) was enough to handle the previous setup, as the process reverted due to an out-of-memory error.

```
[Mon Mar  6 17:04:14 2023] Out of memory: Killed process 3664 (echidna-test) total-vm:1074278180kB, anon-rss:32011756kB, file-rss:0kB, shmem-rss:0kB, UID:1000 pgtables:62808kB oom_score_adj:0
```

In order to guarantee that echidna only calls relevant functions, we cannot use inheritance (`InvariantTest is Vault...`), and we should rather use composition (`Vault private vault = new Vault()` inside the test constructor).

However, since the vault contains separate accounting for each user, we should not use the test contract to directly interact with the vault. To handle that, we use the ["user proxy"](https://github.com/crytic/echidna-streaming-series/blob/main/part3/contracts/crytic/Setup.sol) strategy highlighted in the [Learn how to fuzz like a pro: Intro to AMM’s invariants](https://www.youtube.com/live/n0RaKKVTGvA?feature=share&t=4255) tutorial from Trail of Bits. Essentially, the test contract contains a list of `User` contracts that they interact with the vault themselves. For the sake of simplicity, we choose echidna's users to be the vault depositors and the test contract to be the vault controller. 

### 2. Remove unused parameters from public functions

Echidna will try to fuzz all function parameters to guarantee that different corner cases are caught. This means that a `function foo(uint256 a, address b)` will have both `a` and `b` tested against a large number of values to try to break the invariants. 

The previous implementation of `STETHVaultInvariants` was not efficiently taking this into consideration, as it contained a large number of unused parameters (e.g. `function withdraw(uint256 assets, address, address)` on public/external functions. 

This meant that, although echidna would call these functions with different values for each parameter, they would simply be discarded by the function implementation.

As a result, the test was **not reaching 100% coverage** even after a high number of iterations (10 thousand). This could be seen by analyzing the coverage report (`echidna/corpus/covered.<timestamp>.html`, which had a large number of red-colored lines (meaning, unreached code). 

Analyzing the test coverage was extremely important to understand that, although the test was initially passing after change `1. Change state variables from public to private`, it was not really testing anything, as the relevant pieces of the code were not being executed. 

All unused parameters were removed. For example, `withdraw` became simply `function withdraw(uint256 assets)`.

### 3. Optimize fuzzer performance

Fuzzer inputs are bounded with arithmetic computation in order not to waste fuzzer runs, as suggested by the [Learn how to fuzz like a pro: Fuzzing Arithmetics](https://www.youtube.com/watch?v=9P7sqE6hILM&t=3432s) tutorial from Trail of Bits.

For example, instead of returning if the input is invalid, it is preferred to manipulate the value (with `Math.min`, `Math.max`, `value + 1`, etc.) in order to continue the function flow:

```
// before
    function generateInterest(uint256 a) public {
        if (a == 0) return;
        uint256 addInterest = (totalAssets() / a);
        $asset.generateInterest(addInterest);
    }
```

```
// after
    function positiveRebase(uint256 amount) public {
        amount = Math.min(amount, ($asset.totalSupply() * MAX_INVESTOR_GENERATED_PREMIUM) / vault.DENOMINATOR());
        $asset.rebase(address(vault), int256(amount));
    }
```

### 4. Change logic of "withdrawal after deposit" 

The previous implementation had a mapping of user to `LastDeposit`. If I am not mistaken, there could be a case where a user would deposit at round N, deposit process round N+1, then withdraw at round N+2. In this case, the property check from the test would not be verified.  Because of that, I changed the logic to verify if `vault.totalIdleAssets` is zero (meaning, assets have been processed). I believe the previous problem still exists, but at least the code is cleaner.

### CODE REVIEW

**Comment by aviggiano** [comment]
Having all variables as `public` was generating much more test cases than what we needed, which is why echidna was taking forever to run.

```
Tests found: 70
Seed: 3379254151187803815
Unique instructions: 7551
Unique codehashes: 3
Corpus size: 3
```

For example, none of those made sense to be tested:

```
assertion in INVESTOR_RATIO(): fuzzing (3858/100000)
assertion in controller(): fuzzing (3858/100000)
assertion in $configuration(): fuzzing (3858/100000)
```

Not even an `r3.2xlarge` instance (32 GB RAM) was enough to handle the previous setup.

```
[Mon Mar  6 17:04:14 2023] Out of memory: Killed process 3664 (echidna-test) total-vm:1074278180kB, anon-rss:32011756kB, file-rss:0kB, shmem-rss:0kB, UID:1000 pgtables:62808kB oom_score_adj:0
```

**Comment by aviggiano** [comment]
This PR is still a WIP, I am testing if the following scenario is correctly implemented:

> When a user withdraw/redeem their whole shares, they will always receive more than what they have deposited/minted when withdraw fees are 0%

**Comment by aviggiano** [comment]
Ready to be merged

**Comment by aviggiano** [comment]
Ready to be reviewed @Robsonsjre

**Review by Robsonsjre — COMMENTED** [review]
what is the `codeSize: 0x12000` that you added to echidna config?

**Comment by aviggiano** [comment]
> what is the `codeSize: 0x12000` that you added to echidna config?

Sorry, I forgot to mention it. 

Due to the change `1. Change state variables from public to private`, the code size of the contract was getting bigger than the 24kB limit and the compilation was failing with `MaxCodeSizeExceeded`. Since this isn't actual production code, I just doubled the limit so that tests would run fine.

**Comment by Robsonsjre** [comment]
Good to know! Thanks!

**Pull request merged**
